export enum UserRole {
    ADMIN = '1',
    MANAGER = '2',
    STAFF = '3'
}

export enum HospitalPosition {
  // Leadership & Administration
  HOSPITAL_DIRECTOR = "HOSPITAL_DIRECTOR",
  CHIEF_MEDICAL_OFFICER = "CHIEF_MEDICAL_OFFICER",
  CHIEF_NURSING_OFFICER = "CHIEF_NURSING_OFFICER",
  MEDICAL_DIRECTOR = "MEDICAL_DIRECTOR",
  ADMINISTRATOR = "ADMINISTRATOR",
  OPERATIONS_MANAGER = "OPERATIONS_MANAGER",
  HUMAN_RESOURCES_MANAGER = "HUMAN_RESOURCES_MANAGER",
  FINANCE_MANAGER = "FINANCE_MANAGER",

  // Doctors (generic position)
  PHYSICIAN = "PHYSICIAN",
  SURGEON = "SURGEON",
  RESIDENT_DOCTOR = "RESIDENT_DOCTOR",
  INTERN_DOCTOR = "INTERN_DOCTOR",

  // Nursing
  REGISTERED_NURSE = "REGISTERED_NURSE",
  LICENSED_PRACTICAL_NURSE = "LICENSED_PRACTICAL_NURSE",
  NURSE_PRACTITIONER = "NURSE_PRACTITIONER",
  HEAD_NURSE = "HEAD_NURSE",
  NURSE_MIDWIFE = "NURSE_MIDWIFE",

  // Allied Health
  PHARMACIST = "PHARMACIST",
  PHARMACY_TECHNICIAN = "PHARMACY_TECHNICIAN",
  LAB_TECHNICIAN = "LAB_TECHNICIAN",
  RADIOLOGY_TECHNICIAN = "RADIOLOGY_TECHNICIAN",
  PHYSIOTHERAPIST = "PHYSIOTHERAPIST",
  OCCUPATIONAL_THERAPIST = "OCCUPATIONAL_THERAPIST",
  RESPIRATORY_THERAPIST = "RESPIRATORY_THERAPIST",
  DIETITIAN = "DIETITIAN",
  SPEECH_THERAPIST = "SPEECH_THERAPIST",

  // Emergency & Clinical Support
  PARAMEDIC = "PARAMEDIC",
  EMT = "EMT",
  MEDICAL_ASSISTANT = "MEDICAL_ASSISTANT",
  CLINICAL_ASSISTANT = "CLINICAL_ASSISTANT",

  // IT & Records
  HEALTH_INFORMATICS_OFFICER = "HEALTH_INFORMATICS_OFFICER",
  IT_SUPPORT = "IT_SUPPORT",
  SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR",
  MEDICAL_RECORDS_OFFICER = "MEDICAL_RECORDS_OFFICER",

  // Front Desk & Billing
  RECEPTIONIST = "RECEPTIONIST",
  PATIENT_REGISTRATION_OFFICER = "PATIENT_REGISTRATION_OFFICER",
  BILLING_OFFICER = "BILLING_OFFICER",

  // Facilities
  MAINTENANCE_TECHNICIAN = "MAINTENANCE_TECHNICIAN",
  HOUSEKEEPING_STAFF = "HOUSEKEEPING_STAFF",
  SECURITY_GUARD = "SECURITY_GUARD",
  DRIVER = "DRIVER",
  MORTUARY_ATTENDANT = "MORTUARY_ATTENDANT",

  // Others
  VOLUNTEER = "VOLUNTEER",
  TRAINEE = "TRAINEE"
}
export enum MedicalSpecialty {
  GENERAL_PRACTITIONER = "GENERAL_PRACTITIONER",
  EMERGENCY_PHYSICIAN = "EMERGENCY_PHYSICIAN",
  ANESTHESIOLOGIST = "ANESTHESIOLOGIST",
  PEDIATRICIAN = "PEDIATRICIAN",
  CARDIOLOGIST = "CARDIOLOGIST",
  NEUROLOGIST = "NEUROLOGIST",
  ORTHOPEDIC_SURGEON = "ORTHOPEDIC_SURGEON",
  DERMATOLOGIST = "DERMATOLOGIST",
  PSYCHIATRIST = "PSYCHIATRIST",
  RADIOLOGIST = "RADIOLOGIST",
  PATHOLOGIST = "PATHOLOGIST",
  OBSTETRICIAN_GYNECOLOGIST = "OBSTETRICIAN_GYNECOLOGIST",
  ONCOLOGIST = "ONCOLOGIST",
  ENDOCRINOLOGIST = "ENDOCRINOLOGIST",
  GASTROENTEROLOGIST = "GASTROENTEROLOGIST",
  PULMONOLOGIST = "PULMONOLOGIST",
  NEPHROLOGIST = "NEPHROLOGIST",
  UROLOGIST = "UROLOGIST",
  OPHTHALMOLOGIST = "OPHTHALMOLOGIST",
  OTOLARYNGOLOGIST = "OTOLARYNGOLOGIST",
  INFECTIOUS_DISEASE_SPECIALIST = "INFECTIOUS_DISEASE_SPECIALIST",
  RHEUMATOLOGIST = "RHEUMATOLOGIST",
  HEMATOLOGIST = "HEMATOLOGIST",
  IMMUNOLOGIST = "IMMUNOLOGIST",
  GERIATRICIAN = "GERIATRICIAN",
  NEONATOLOGIST = "NEONATOLOGIST",
  PAIN_MANAGEMENT_SPECIALIST = "PAIN_MANAGEMENT_SPECIALIST",
  INTENSIVIST = "INTENSIVIST",
  SPORTS_MEDICINE_PHYSICIAN = "SPORTS_MEDICINE_PHYSICIAN",
  PHYSIATRIST = "PHYSIATRIST"
}
