// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type LoginGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['index'], false>
}
type LoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth_validator.ts')['LoginValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['login'], true>
}
type LogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['logout'], false>
}
type DashboardGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/dashboard_controller.ts').default['index'], false>
}
type DashboardOverviewGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/dashboard_controller.ts').default['overview'], false>
}
type DashboardOverviewProductIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/dashboard_controller.ts').default['product_overview'], false>
}
type DashboardPharmaciesStorePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/pharmacy_validator.ts')['createPharmacyValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/pharmacies_controller.ts').default['store'], true>
}
type DashboardPharmaciesUpdatePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/pharmacies_controller.ts').default['update'], false>
}
type DashboardPharmaciesListGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/pharmacies_controller.ts').default['list'], false>
}
type DashboardPharmaciesNewGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/pharmacies_controller.ts').default['new_view'], false>
}
type DashboardPharmaciesEditIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/pharmacies_controller.ts').default['edit'], false>
}
type DashboardPharmaciesIdRepresentativeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/pharmacies_controller.ts').default['representative_view'], false>
}
type DashboardPharmaciesBranchesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/branches_controller.ts').default['branches_view'], false>
}
type DashboardTransportersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/transporters_controller.ts').default['list'], false>
}
type DashboardTransportersStorePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/transporters_controller.ts').default['store'], false>
}
type DashboardTransportersUpdatePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/transporters_controller.ts').default['update'], false>
}
type DashboardLocationsListGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/locations_controller.ts').default['list'], false>
}
type DashboardLocationsAddPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/locations_controller.ts').default['add'], false>
}
type DashboardStaffsListGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['list_staffs'], false>
}
type DashboardStaffsNewGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['new_staff'], false>
}
type DashboardStaffsCreatePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['create_staff'], false>
}
type DashboardStaffsEditIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['edit_staff'], false>
}
type DashboardStaffsUpdatePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['update_staff'], false>
}
type DashboardFacilitiesListGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['list_facilities'], false>
}
type DashboardFacilitiesNewGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['new_facility'], false>
}
type DashboardFacilitiesCreatePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['create_facility'], false>
}
type DashboardFacilitiesEditIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['edit_facility'], false>
}
type DashboardFacilitiesUpdatePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/prescriptions_controller.ts').default['update_facility'], false>
}
type DashboardProductsListGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/products_controller.ts').default['list'], false>
}
type DashboardProductsNewGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/products_controller.ts').default['new_product'], false>
}
type DashboardProductsCreateManyPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/product_validator.ts')['createManyProductValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/products_controller.ts').default['create_many'], true>
}
type DashboardProductsCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/product_validator.ts')['createProductValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/products_controller.ts').default['create'], true>
}
type DashboardProductsEditIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/products_controller.ts').default['edit'], false>
}
type DashboardProductsUpdatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/product_validator.ts')['updateProductValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/products_controller.ts').default['update'], true>
}
type DashboardInsuranceIndexGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/insurances_controller.ts').default['index'], false>
}
type DashboardInsuranceProductsStorePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/insurance_products_controller.ts').default['store'], false>
}
type DashboardInsuranceProductsDeletePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/insurance_products_controller.ts').default['delete'], false>
}
type DashboardInsuranceProductsSyncPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/insurance_products_controller.ts').default['sync'], false>
}
type DashboardNotificationsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/notifications_controller.ts').default['index'], false>
}
type DashboardAdsBasicGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/basic_ads_controller.ts').default['list'], false>
}
type DashboardAdsBasicCheckPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/basic_ads_controller.ts').default['check_client'], false>
}
type DashboardAdsBasicStorePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/basic_ads_controller.ts').default['store'], false>
}
type DashboardAdsBasicDeleteIdPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/basic_ads_controller.ts').default['destroy'], false>
}
type DashboardSettingsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/app_settings_controller.ts').default['list'], false>
}
type DashboardSettingsActivePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/app_settings_controller.ts').default['active'], false>
}
type NotificationsListGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/notifications_controller.ts').default['list'], false>
}
type NotificationsReadIdPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/notifications_controller.ts').default['read'], false>
}
export interface ApiDefinition {
  'login': {
    '$url': {
    };
    '$get': LoginGetHead;
    '$head': LoginGetHead;
    '$post': LoginPost;
  };
  'logout': {
    '$url': {
    };
    '$post': LogoutPost;
  };
  'dashboard': {
    '$url': {
    };
    '$get': DashboardGetHead;
    '$head': DashboardGetHead;
    'overview': {
      '$url': {
      };
      '$get': DashboardOverviewGetHead;
      '$head': DashboardOverviewGetHead;
      'product': {
        ':id': {
          '$url': {
          };
          '$get': DashboardOverviewProductIdGetHead;
          '$head': DashboardOverviewProductIdGetHead;
        };
      };
    };
    'pharmacies': {
      'store': {
        '$url': {
        };
        '$post': DashboardPharmaciesStorePost;
      };
      'update': {
        '$url': {
        };
        '$post': DashboardPharmaciesUpdatePost;
      };
      'list': {
        '$url': {
        };
        '$get': DashboardPharmaciesListGetHead;
        '$head': DashboardPharmaciesListGetHead;
      };
      'new': {
        '$url': {
        };
        '$get': DashboardPharmaciesNewGetHead;
        '$head': DashboardPharmaciesNewGetHead;
      };
      'edit': {
        ':id': {
          '$url': {
          };
          '$get': DashboardPharmaciesEditIdGetHead;
          '$head': DashboardPharmaciesEditIdGetHead;
        };
      };
      ':id': {
        'representative': {
          '$url': {
          };
          '$get': DashboardPharmaciesIdRepresentativeGetHead;
          '$head': DashboardPharmaciesIdRepresentativeGetHead;
        };
      };
      'branches': {
        ':id': {
          '$url': {
          };
          '$get': DashboardPharmaciesBranchesIdGetHead;
          '$head': DashboardPharmaciesBranchesIdGetHead;
        };
      };
    };
    'transporters': {
      '$url': {
      };
      '$get': DashboardTransportersGetHead;
      '$head': DashboardTransportersGetHead;
      'store': {
        '$url': {
        };
        '$post': DashboardTransportersStorePost;
      };
      'update': {
        '$url': {
        };
        '$post': DashboardTransportersUpdatePost;
      };
    };
    'locations': {
      'list': {
        '$url': {
        };
        '$get': DashboardLocationsListGetHead;
        '$head': DashboardLocationsListGetHead;
      };
      'add': {
        '$url': {
        };
        '$post': DashboardLocationsAddPost;
      };
    };
    'staffs': {
      'list': {
        '$url': {
        };
        '$get': DashboardStaffsListGetHead;
        '$head': DashboardStaffsListGetHead;
      };
      'new': {
        '$url': {
        };
        '$get': DashboardStaffsNewGetHead;
        '$head': DashboardStaffsNewGetHead;
      };
      'create': {
        '$url': {
        };
        '$post': DashboardStaffsCreatePost;
      };
      'edit': {
        ':id': {
          '$url': {
          };
          '$get': DashboardStaffsEditIdGetHead;
          '$head': DashboardStaffsEditIdGetHead;
        };
      };
      'update': {
        '$url': {
        };
        '$post': DashboardStaffsUpdatePost;
      };
    };
    'facilities': {
      'list': {
        '$url': {
        };
        '$get': DashboardFacilitiesListGetHead;
        '$head': DashboardFacilitiesListGetHead;
      };
      'new': {
        '$url': {
        };
        '$get': DashboardFacilitiesNewGetHead;
        '$head': DashboardFacilitiesNewGetHead;
      };
      'create': {
        '$url': {
        };
        '$post': DashboardFacilitiesCreatePost;
      };
      'edit': {
        ':id': {
          '$url': {
          };
          '$get': DashboardFacilitiesEditIdGetHead;
          '$head': DashboardFacilitiesEditIdGetHead;
        };
      };
      'update': {
        '$url': {
        };
        '$post': DashboardFacilitiesUpdatePost;
      };
    };
    'products': {
      'list': {
        '$url': {
        };
        '$get': DashboardProductsListGetHead;
        '$head': DashboardProductsListGetHead;
      };
      'new': {
        '$url': {
        };
        '$get': DashboardProductsNewGetHead;
        '$head': DashboardProductsNewGetHead;
      };
      'create': {
        'many': {
          '$url': {
          };
          '$post': DashboardProductsCreateManyPost;
        };
        '$url': {
        };
        '$post': DashboardProductsCreatePost;
      };
      'edit': {
        ':id': {
          '$url': {
          };
          '$get': DashboardProductsEditIdGetHead;
          '$head': DashboardProductsEditIdGetHead;
        };
      };
      'update': {
        '$url': {
        };
        '$post': DashboardProductsUpdatePost;
      };
    };
    'insurance': {
      'index': {
        '$url': {
        };
        '$get': DashboardInsuranceIndexGetHead;
        '$head': DashboardInsuranceIndexGetHead;
      };
      'products': {
        'store': {
          '$url': {
          };
          '$post': DashboardInsuranceProductsStorePost;
        };
        'delete': {
          '$url': {
          };
          '$post': DashboardInsuranceProductsDeletePost;
        };
        'sync': {
          '$url': {
          };
          '$post': DashboardInsuranceProductsSyncPost;
        };
      };
    };
    'notifications': {
      '$url': {
      };
      '$get': DashboardNotificationsGetHead;
      '$head': DashboardNotificationsGetHead;
    };
    'ads': {
      'basic': {
        '$url': {
        };
        '$get': DashboardAdsBasicGetHead;
        '$head': DashboardAdsBasicGetHead;
        'check': {
          '$url': {
          };
          '$post': DashboardAdsBasicCheckPost;
        };
        'store': {
          '$url': {
          };
          '$post': DashboardAdsBasicStorePost;
        };
        'delete': {
          ':id': {
            '$url': {
            };
            '$post': DashboardAdsBasicDeleteIdPost;
          };
        };
      };
    };
    'settings': {
      '$url': {
      };
      '$get': DashboardSettingsGetHead;
      '$head': DashboardSettingsGetHead;
      'active': {
        '$url': {
        };
        '$post': DashboardSettingsActivePost;
      };
    };
  };
  'notifications': {
    'list': {
      '$url': {
      };
      '$get': NotificationsListGetHead;
      '$head': NotificationsListGetHead;
    };
    'read': {
      ':id': {
        '$url': {
        };
        '$post': NotificationsReadIdPost;
      };
    };
  };
}
const routes = [
  {
    params: ["*"],
    name: 'drive.fs.serve',
    path: '/uploads/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'auth.index',
    path: '/login',
    method: ["GET","HEAD"],
    types: {} as LoginGetHead,
  },
  {
    params: [],
    name: 'auth.login',
    path: '/login',
    method: ["POST"],
    types: {} as LoginPost,
  },
  {
    params: [],
    name: 'auth.logout',
    path: '/logout',
    method: ["POST"],
    types: {} as LogoutPost,
  },
  {
    params: [],
    name: 'dashboard.index',
    path: '/dashboard',
    method: ["GET","HEAD"],
    types: {} as DashboardGetHead,
  },
  {
    params: [],
    name: 'dashboard.overview',
    path: '/dashboard/overview',
    method: ["GET","HEAD"],
    types: {} as DashboardOverviewGetHead,
  },
  {
    params: ["id"],
    name: 'dashboard.overview.product',
    path: '/dashboard/overview/product/:id',
    method: ["GET","HEAD"],
    types: {} as DashboardOverviewProductIdGetHead,
  },
  {
    params: [],
    name: 'dashboard.pharamacies.store',
    path: '/dashboard/pharmacies/store',
    method: ["POST"],
    types: {} as DashboardPharmaciesStorePost,
  },
  {
    params: [],
    name: 'dashboard.pharamacies.update',
    path: '/dashboard/pharmacies/update',
    method: ["POST"],
    types: {} as DashboardPharmaciesUpdatePost,
  },
  {
    params: [],
    name: 'dashboard.pharmacies.list',
    path: '/dashboard/pharmacies/list',
    method: ["GET","HEAD"],
    types: {} as DashboardPharmaciesListGetHead,
  },
  {
    params: [],
    name: 'dashboard.pharmacies.new.view',
    path: '/dashboard/pharmacies/new',
    method: ["GET","HEAD"],
    types: {} as DashboardPharmaciesNewGetHead,
  },
  {
    params: ["id"],
    name: 'dashboard.pharmacies.edit',
    path: '/dashboard/pharmacies/edit/:id',
    method: ["GET","HEAD"],
    types: {} as DashboardPharmaciesEditIdGetHead,
  },
  {
    params: ["id"],
    name: 'dashboard.pharamacies.representative.view',
    path: '/dashboard/pharmacies/:id/representative',
    method: ["GET","HEAD"],
    types: {} as DashboardPharmaciesIdRepresentativeGetHead,
  },
  {
    params: ["id"],
    name: 'dashboard.branches.view',
    path: '/dashboard/pharmacies/branches/:id',
    method: ["GET","HEAD"],
    types: {} as DashboardPharmaciesBranchesIdGetHead,
  },
  {
    params: [],
    name: 'dashboard.transporters.list',
    path: '/dashboard/transporters',
    method: ["GET","HEAD"],
    types: {} as DashboardTransportersGetHead,
  },
  {
    params: [],
    name: 'dashboard.transporters.store',
    path: '/dashboard/transporters/store',
    method: ["POST"],
    types: {} as DashboardTransportersStorePost,
  },
  {
    params: [],
    name: 'dashboard.transporters.update',
    path: '/dashboard/transporters/update',
    method: ["POST"],
    types: {} as DashboardTransportersUpdatePost,
  },
  {
    params: [],
    name: 'dashboard.locations.list',
    path: '/dashboard/locations/list',
    method: ["GET","HEAD"],
    types: {} as DashboardLocationsListGetHead,
  },
  {
    params: [],
    name: 'dashboard.locations.add',
    path: '/dashboard/locations/add',
    method: ["POST"],
    types: {} as DashboardLocationsAddPost,
  },
  {
    params: [],
    name: 'dashboard.staffs.list',
    path: '/dashboard/staffs/list',
    method: ["GET","HEAD"],
    types: {} as DashboardStaffsListGetHead,
  },
  {
    params: [],
    name: 'dashboard.staffs.new',
    path: '/dashboard/staffs/new',
    method: ["GET","HEAD"],
    types: {} as DashboardStaffsNewGetHead,
  },
  {
    params: [],
    name: 'dashboard.staffs.create',
    path: '/dashboard/staffs/create',
    method: ["POST"],
    types: {} as DashboardStaffsCreatePost,
  },
  {
    params: ["id"],
    name: 'dashboard.staffs.edit',
    path: '/dashboard/staffs/edit/:id',
    method: ["GET","HEAD"],
    types: {} as DashboardStaffsEditIdGetHead,
  },
  {
    params: [],
    name: 'dashboard.staffs.update',
    path: '/dashboard/staffs/update',
    method: ["POST"],
    types: {} as DashboardStaffsUpdatePost,
  },
  {
    params: [],
    name: 'dashboard.facilities.list',
    path: '/dashboard/facilities/list',
    method: ["GET","HEAD"],
    types: {} as DashboardFacilitiesListGetHead,
  },
  {
    params: [],
    name: 'dashboard.facilities.new',
    path: '/dashboard/facilities/new',
    method: ["GET","HEAD"],
    types: {} as DashboardFacilitiesNewGetHead,
  },
  {
    params: [],
    name: 'dashboard.facilities.create',
    path: '/dashboard/facilities/create',
    method: ["POST"],
    types: {} as DashboardFacilitiesCreatePost,
  },
  {
    params: ["id"],
    name: 'dashboard.facilities.edit',
    path: '/dashboard/facilities/edit/:id',
    method: ["GET","HEAD"],
    types: {} as DashboardFacilitiesEditIdGetHead,
  },
  {
    params: [],
    name: 'dashboard.facilities.update',
    path: '/dashboard/facilities/update',
    method: ["POST"],
    types: {} as DashboardFacilitiesUpdatePost,
  },
  {
    params: [],
    name: 'dashboard.products.list',
    path: '/dashboard/products/list',
    method: ["GET","HEAD"],
    types: {} as DashboardProductsListGetHead,
  },
  {
    params: [],
    name: 'dashboard.products.new',
    path: '/dashboard/products/new',
    method: ["GET","HEAD"],
    types: {} as DashboardProductsNewGetHead,
  },
  {
    params: [],
    name: 'dashboard.products.create.many',
    path: '/dashboard/products/create/many',
    method: ["POST"],
    types: {} as DashboardProductsCreateManyPost,
  },
  {
    params: [],
    name: 'dashboard.products.create',
    path: '/dashboard/products/create',
    method: ["POST"],
    types: {} as DashboardProductsCreatePost,
  },
  {
    params: ["id"],
    name: 'dashboard.products.edit',
    path: '/dashboard/products/edit/:id',
    method: ["GET","HEAD"],
    types: {} as DashboardProductsEditIdGetHead,
  },
  {
    params: [],
    name: 'dashboard.products.update',
    path: '/dashboard/products/update',
    method: ["POST"],
    types: {} as DashboardProductsUpdatePost,
  },
  {
    params: [],
    name: 'dashboard.insurance.index',
    path: '/dashboard/insurance/index',
    method: ["GET","HEAD"],
    types: {} as DashboardInsuranceIndexGetHead,
  },
  {
    params: [],
    name: 'dashboard.insurance.products.store',
    path: '/dashboard/insurance/products/store',
    method: ["POST"],
    types: {} as DashboardInsuranceProductsStorePost,
  },
  {
    params: [],
    name: 'dashboard.insurance.products.delete',
    path: '/dashboard/insurance/products/delete',
    method: ["POST"],
    types: {} as DashboardInsuranceProductsDeletePost,
  },
  {
    params: [],
    name: 'dashboard.insurance.products.sync',
    path: '/dashboard/insurance/products/sync',
    method: ["POST"],
    types: {} as DashboardInsuranceProductsSyncPost,
  },
  {
    params: [],
    name: 'dashboard.notifications.list',
    path: '/dashboard/notifications',
    method: ["GET","HEAD"],
    types: {} as DashboardNotificationsGetHead,
  },
  {
    params: [],
    name: 'dashboard.ads.basic.list',
    path: '/dashboard/ads/basic',
    method: ["GET","HEAD"],
    types: {} as DashboardAdsBasicGetHead,
  },
  {
    params: [],
    name: 'dashboard.ads.basic.check.client',
    path: '/dashboard/ads/basic/check',
    method: ["POST"],
    types: {} as DashboardAdsBasicCheckPost,
  },
  {
    params: [],
    name: 'dashboard.ads.basic.store',
    path: '/dashboard/ads/basic/store',
    method: ["POST"],
    types: {} as DashboardAdsBasicStorePost,
  },
  {
    params: ["id"],
    name: 'dashboard.ads.basic.delete',
    path: '/dashboard/ads/basic/delete/:id',
    method: ["POST"],
    types: {} as DashboardAdsBasicDeleteIdPost,
  },
  {
    params: [],
    name: 'dashboard.settings.list',
    path: '/dashboard/settings',
    method: ["GET","HEAD"],
    types: {} as DashboardSettingsGetHead,
  },
  {
    params: [],
    name: 'dashboard.settings.active',
    path: '/dashboard/settings/active',
    method: ["POST"],
    types: {} as DashboardSettingsActivePost,
  },
  {
    params: [],
    name: 'notifications.list',
    path: '/notifications/list',
    method: ["GET","HEAD"],
    types: {} as NotificationsListGetHead,
  },
  {
    params: ["id"],
    name: 'notifications.read',
    path: '/notifications/read/:id',
    method: ["POST"],
    types: {} as NotificationsReadIdPost,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
