version: '3.8'

services:
  backoffice-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vura_backoffice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
