import { ReceiptAction } from '#actions/receipt_action'
import User from '#models/user'
import env from '#start/env'
import { PrintPaperSize } from '#types/index'
import type { HttpContext } from '@adonisjs/core/http'
import vine from '@vinejs/vine'

export default class ReceiptsController {
  async receipt({ request, response, auth, view }: HttpContext) {
    const validator = vine.compile(
      vine.object({
        size: vine.enum(Object.values(PrintPaperSize)).optional(),
        title: vine.string().minLength(3).maxLength(100),
      })
    )
    const payload = await request.validateUsing(validator)

    try {
      const usr = auth.user as User
      const id = request.param('id') || -1

      const receipt = await usr
        .related('receipts')
        .query()
        .andWhere('user_id', usr.id)
        .andWhere('sale_id', id)
        .preload('sale')
        .firstOrFail()

      const sale = receipt.sale

      await receipt.delete()

      const paperSize = payload.size || PrintPaperSize.A4
      const html = await view.render('receipts/index', { sale, paperSize })
      const path = await ReceiptAction.generatePdf(payload.title, html, paperSize)
      return response.download(path)
    } catch (error) {
      console.error(error)
      return { error: 'Receipt Not Found' }
    }
  }

  async receipt_design_test({ response, view }: HttpContext) {
    if (env.get('NODE_ENV') != 'development') return response.forbidden()

    //Normal Sale NS
    // const NS = {
    //   id: '0220d2c2-9fdf-469a-859b-4c3adb383c9f',
    //   userId: 'b9ab132a-262f-4a66-8ecc-d5c0ad5a71ed',
    //   tin: 999909100,
    //   branchId: '00',
    //   invoiceNo: 51,
    //   originalInvoiceNo: null,
    //   customerTin: null,
    //   purchaseCode: null,
    //   customerName: 'pharma0',
    //   saleType: 'N',
    //   receiptType: 'S',
    //   paymentMethod: '01',
    //   saleStatus: '02',
    //   confirmationDate: '2025-03-24 15:06:33+02',
    //   saleDate: '2025-03-24',
    //   stockReleaseDate: '2025-03-24 15:06:33+02',
    //   cancelRequestDate: null,
    //   canceledDate: null,
    //   refundDate: null,
    //   refundReason: null,
    //   totalItems: 2,
    //   taxableAmountA: 20.0,
    //   taxableAmountB: 0.0,
    //   taxableAmountC: 0.0,
    //   taxableAmountD: 0.0,
    //   taxRateA: 0.0,
    //   taxRateB: 18.0,
    //   taxRateC: 0.0,
    //   taxRateD: 0.0,
    //   taxAmountA: 0.0,
    //   taxAmountB: 0.0,
    //   taxAmountC: 0.0,
    //   taxAmountD: 0.0,
    //   totalTaxableAmount: 20.0,
    //   totalTaxAmount: 0.0,
    //   totalAmount: 20.0,
    //   itemsReceived: 'Y',
    //   remark: null,
    //   registrantName: 'company_test',
    //   registrantId: 'LV12001',
    //   modifierId: 'LV12001',
    //   modifierName: 'company_test',

    //   receipt: {
    //     customerMobileNo: '0780233560',
    //     reportNo: 1,
    //     tradeName: 'YB Trade Name',
    //     address: 'Kigali',
    //     topMessage: 'Thank you for your purchase!',
    //     bottomMessage: 'Visit us again!',
    //     itemReceived: 'Y',
    //   },

    //   items: {
    //     data: [
    //       {
    //         sequenceNo: 1,
    //         classificationCode: 'RW2NTBA0003',
    //         name: 'Product A',
    //         packageUnit: 'BQ',
    //         packageNo: 1,
    //         quantityUnit: 'TU',
    //         quantity: 1,
    //         price: 10,
    //         supplyPrice: 10,
    //         discountRate: 0,
    //         taxationType: 'A',
    //         discountAmount: 0,
    //         taxAmount: 0,
    //         taxableAmount: 10,
    //         totalAmount: 10,
    //       },
    //       {
    //         sequenceNo: 2,
    //         code: 'ITEM002',
    //         classificationCode: 'RW2NTBA0004',
    //         name: 'Product B',
    //         barcode: '987654321098',
    //         packageUnit: 'JR',
    //         packageNo: 1,
    //         quantityUnit: 'MGM',
    //         quantity: 1,
    //         price: 10,
    //         supplyPrice: 10,
    //         discountRate: 0,
    //         taxationType: 'A',
    //         discountAmount: 0,
    //         taxAmount: 0,
    //         taxableAmount: 10,
    //         totalAmount: 10,
    //       },
    //     ],
    //   },

    //   ebmSaleData: {
    //     rcptNo: 51,
    //     intrlData: 'RYZCGMGMAEZBRVRTTNRWJRXVBQ',
    //     rcptSign: 'UIQSPIC5ROJQYTVX',
    //     totRcptNo: 51,
    //     vsdcRcptPbctDate: '20250406200536',
    //     sdcId: 'SDC012000001',
    //     mrcNo: 'WIS00000064',
    //   },

    //   ebmApiVersion: '1.0',
    //   createdAt: '2025-04-06 20:05:39.146+02',
    //   updatedAt: '2025-04-06 20:05:39.145+02',
    // }

    // //Normal Refund RS
    // const NR = {
    //   id: '6922724a-b646-41eb-8a43-2b12794d187f',
    //   userId: '0dab9adc-af54-41b3-944f-17c6e7bd9d7c',
    //   tin: 999909101,
    //   branchId: '00',
    //   invoiceNo: 82,
    //   originalInvoiceNo: 81,
    //   customerTin: null,
    //   purchaseCode: null,
    //   customerName: 'pharma0',
    //   saleType: 'N',
    //   receiptType: 'R',
    //   paymentMethod: '01',
    //   saleStatus: '02',
    //   confirmationDate: '2025-04-09 13:58:46+02',
    //   saleDate: '2025-03-24',
    //   stockReleaseDate: '2025-04-09 13:58:46+02',
    //   cancelRequestDate: null,
    //   canceledDate: null,
    //   refundDate: '2025-04-09 13:58:46.796+02',
    //   refundReason: '01',
    //   totalItems: 1,
    //   taxableAmountA: 0.0,
    //   taxableAmountB: 44000.0,
    //   taxableAmountC: 0.0,
    //   taxableAmountD: 0.0,
    //   taxRateA: 0.0,
    //   taxRateB: 18.0,
    //   taxRateC: 0.0,
    //   taxRateD: 0.0,
    //   taxAmountA: 0.0,
    //   taxAmountB: 6711.86,
    //   taxAmountC: 0.0,
    //   taxAmountD: 0.0,
    //   totalTaxableAmount: 44000.0,
    //   totalTaxAmount: 6711.86,
    //   totalAmount: 44000.0,
    //   itemsReceived: 'Y',
    //   remark: 'because of test',
    //   registrantName: 'Pharma Top',
    //   registrantId: 'LV12002',
    //   modifierId: 'LV12002',
    //   modifierName: 'Pharma Top',
    //   receipt: {
    //     customerTin: 123456789,
    //     customerMobileNo: '0780233560',
    //     reportNo: 1,
    //     tradeName: 'YB Trade Name',
    //     address: 'Kigali',
    //     bottomMessage: 'Thanks see you again!',
    //     itemReceived: 'Y',
    //   },
    //   items: {
    //     data: [
    //       {
    //         extra: {
    //           stockId: 'ABC123',
    //         },
    //         sequenceNo: 1,
    //         classificationCode: 'RW2NTBA00111',
    //         name: 'Product A',
    //         packageUnit: 'BQ',
    //         packageNo: 1,
    //         quantityUnit: 'TU',
    //         quantity: 1,
    //         price: 50000,
    //         supplyPrice: 50000,
    //         discountRate: 12,
    //         taxationType: 'B',
    //         discountAmount: 6000,
    //         taxAmount: 6711.86,
    //         taxableAmount: 44000,
    //         totalAmount: 44000,
    //       },
    //     ],
    //   },
    //   ebmSaleData: {
    //     rcptNo: 82,
    //     intrlData: 'AYYFUYZUAMUBBWVKV5CNTXP22Y',
    //     rcptSign: 'JXT6U6HUDADPMKBS',
    //     totRcptNo: 82,
    //     vsdcRcptPbctDate: '20250409135847',
    //     sdcId: 'SDC012000001',
    //     mrcNo: 'WIS00000064',
    //   },
    //   ebmApiVersion: '1.0',
    //   createdAt: '2025-04-09 13:58:49.48+02',
    //   updatedAt: '2025-04-09 13:58:49.48+02',
    //   extraHeaders: null,
    // }

    // const CS = {
    //   id: '20cbcb5c-1d6e-4b78-b102-82fad183439b',
    //   userId: '0dab9adc-af54-41b3-944f-17c6e7bd9d7c',
    //   tin: 999909101,
    //   branchId: '00',
    //   invoiceNo: 87,
    //   originalInvoiceNo: null,
    //   customerTin: null,
    //   purchaseCode: null,
    //   customerName: 'pharma0',
    //   saleType: 'C',
    //   receiptType: 'S',
    //   paymentMethod: '01',
    //   saleStatus: '02',
    //   confirmationDate: '2025-03-24 15:06:33+02',
    //   saleDate: '2025-03-24',
    //   stockReleaseDate: '2025-03-24 15:06:33+02',
    //   cancelRequestDate: null,
    //   canceledDate: null,
    //   refundDate: null,
    //   refundReason: null,
    //   totalItems: 2,
    //   taxableAmountA: 9.5,
    //   taxableAmountB: 44000.0,
    //   taxableAmountC: 0.0,
    //   taxableAmountD: 0.0,
    //   taxRateA: 0.0,
    //   taxRateB: 18.0,
    //   taxRateC: 0.0,
    //   taxRateD: 0.0,
    //   taxAmountA: 0.0,
    //   taxAmountB: 6711.86,
    //   taxAmountC: 0.0,
    //   taxAmountD: 0.0,
    //   totalTaxableAmount: 44009.5,
    //   totalTaxAmount: 6711.86,
    //   totalAmount: 44009.5,
    //   itemsReceived: 'Y',
    //   remark: null,
    //   registrantName: 'Pharma Top',
    //   registrantId: 'LV12002',
    //   modifierId: 'LV12002',
    //   modifierName: 'Pharma Top',
    //   receipt: {
    //     customerTin: 123456789,
    //     customerMobileNo: '0780233560',
    //     reportNo: 1,
    //     tradeName: 'YB Trade Name',
    //     address: 'Kigali',
    //     bottomMessage: 'Thanks see you again!',
    //     itemReceived: 'Y',
    //   },
    //   items: {
    //     data: [
    //       {
    //         extra: { stock_id: 'ABC123' },
    //         sequenceNo: 1,
    //         classificationCode: 'RW2NTBA00115',
    //         name: 'Product A',
    //         packageUnit: 'BQ',
    //         packageNo: 1,
    //         quantityUnit: 'TU',
    //         quantity: 1,
    //         price: 50000,
    //         supplyPrice: 50000,
    //         discountRate: 12,
    //         taxationType: 'B',
    //         discountAmount: 6000,
    //         taxAmount: 6711.86,
    //         taxableAmount: 44000,
    //         totalAmount: 44000,
    //       },
    //       {
    //         extra: { stock_id: 'KKK45' },
    //         sequenceNo: 2,
    //         code: 'ITEM002',
    //         classificationCode: 'RW2NTBA00116',
    //         name: 'Product B',
    //         barcode: '987654321098',
    //         packageUnit: 'JR',
    //         packageNo: 1,
    //         quantityUnit: 'MGM',
    //         quantity: 1,
    //         price: 10,
    //         supplyPrice: 10,
    //         discountRate: 5,
    //         taxationType: 'A',
    //         expirationDate: '12/12/2028',
    //         discountAmount: 0.5,
    //         taxAmount: 0,
    //         taxableAmount: 9.5,
    //         totalAmount: 9.5,
    //       },
    //     ],
    //   },
    //   ebmSaleData: {
    //     rcptNo: 85,
    //     intrlData: 'O7YNB4FM5LOCUVUIL7ZOMR6NMU',
    //     rcptSign: 'OCFEZRO3RC7ZLT3N',
    //     totRcptNo: 85,
    //     vsdcRcptPbctDate: '20250409152252',
    //     sdcId: 'SDC012000001',
    //     mrcNo: 'WIS00000064',
    //   },
    //   ebmApiVersion: '1.0',
    //   createdAt: '2025-04-09 16:49:52.071+02',
    //   updatedAt: '2025-04-09 16:49:52.071+02',
    //   extraHeaders: ['stock_id'],
    // }

    const CR = {
      id: '240fa893-4fb1-474a-aab9-94181d81d33d',
      userId: '0dab9adc-af54-41b3-944f-17c6e7bd9d7c',
      tin: 999909101,
      branchId: '00',
      invoiceNo: 89,
      originalInvoiceNo: 85,
      customerTin: null,
      purchaseCode: null,
      customerName: 'pharma0',
      saleType: 'C',
      receiptType: 'R',
      paymentMethod: '01',
      saleStatus: '02',
      confirmationDate: '2025-04-09 17:11:10+02',
      saleDate: '2025-03-24',
      stockReleaseDate: '2025-04-09 17:11:10+02',
      cancelRequestDate: null,
      canceledDate: null,
      refundDate: '2025-04-09 17:11:10.907+02',
      refundReason: '01',
      totalItems: 2,
      taxableAmountA: 9.5,
      taxableAmountB: 44000.0,
      taxableAmountC: 0.0,
      taxableAmountD: 0.0,
      taxRateA: 0.0,
      taxRateB: 18.0,
      taxRateC: 0.0,
      taxRateD: 0.0,
      taxAmountA: 0.0,
      taxAmountB: 6711.86,
      taxAmountC: 0.0,
      taxAmountD: 0.0,
      totalTaxableAmount: 44009.5,
      totalTaxAmount: 6711.86,
      totalAmount: 44009.5,
      itemsReceived: 'Y',
      remark: 'because of test',
      registrantName: 'Pharma Top',
      registrantId: 'LV12002',
      modifierId: 'LV12002',
      modifierName: 'Pharma Top',
      receipt: {
        customerTin: 123456789,
        customerMobileNo: '0780233560',
        reportNo: 1,
        tradeName: 'YB Trade Name',
        address: 'Kigali',
        bottomMessage: 'Thanks see you again!',
        itemReceived: 'Y',
      },
      items: {
        data: [
          {
            extra: { stock_id: 'ABC123' },
            sequenceNo: 1,
            classificationCode: 'RW2NTBA00115',
            name: 'Product A',
            packageUnit: 'BQ',
            packageNo: 1,
            quantityUnit: 'TU',
            quantity: 1,
            price: 50000,
            supplyPrice: 50000,
            discountRate: 12,
            taxationType: 'B',
            discountAmount: 6000,
            taxAmount: 6711.86,
            taxableAmount: 44000,
            totalAmount: 44000,
          },
          {
            extra: { stock_id: 'KKK45' },
            sequenceNo: 2,
            code: 'ITEM002',
            classificationCode: 'RW2NTBA00116',
            name: 'Product B',
            barcode: '987654321098',
            packageUnit: 'JR',
            packageNo: 1,
            quantityUnit: 'MGM',
            quantity: 1,
            price: 10,
            supplyPrice: 10,
            discountRate: 5,
            taxationType: 'A',
            expirationDate: '12/12/2028',
            discountAmount: 0.5,
            taxAmount: 0,
            taxableAmount: 9.5,
            totalAmount: 9.5,
          },
        ],
      },
      ebmSaleData: {
        rcptNo: 88,
        intrlData: 'EHB4TNDIHU4NVGT4DGAZZFZQFI',
        rcptSign: 'FSIISASIRFOBQX4F',
        totRcptNo: 88,
        vsdcRcptPbctDate: '20250409171115',
        sdcId: 'SDC012000001',
        mrcNo: 'WIS00000064',
      },
      ebmApiVersion: '1.0',
      createdAt: '2025-04-09 17:13:00.856+02',
      updatedAt: '2025-04-09 17:13:00.856+02',
      extraHeaders: 'stock_id',
    }

    const user = {
      id: 'b9ab132a-262f-4a66-8ecc-d5c0ad5a71ed',
      email: 'test@test.com',
      password:
        '$scrypt$n=16384,r=8,p=1$hqvflYk5w7NMAj84wh4uyA$HhZUsZFebLGZ6cF/5xnwXm8NTaLSSV/k7whqDEx334najhy/MQmtKpCbaBc7Y9oLwMSZZVqmbgIW+wihidpxmw',
      fullName: 'test',
      serialNo: 'LV12001',
      mrc: 'ybgroupvsdctest',
      taxPayerName: 'company_test',
      tin: '999909100',
      phoneNumber: '0712355631',
      province: 'kigali',
      district: 'kicukiro',
      sector: 'kicukiro',
      address: 'kk 505 st',
      createdAt: '2025-04-06 20:03:40.059+02',
      updatedAt: '2025-04-06 20:03:40.059+02',
      imageLink:
        'https://images.unsplash.com/photo-1742615869881-95b71cee478c?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    }

    //FIXME: add postal box in user model and table in db  (postalBox)
    return view.render('receipts/design_test', { sale: CR, auth: { user } })
  }
}
